apiVersion: opsd.io/catalog/v1alpha1
kind: KubernetesModuleCatalog

modules:
  - id: argocd
    path: modules/bootstrap/argocd/module.yaml
  - id: cert-manager
    path: modules/infrastructure/cert-manager/module.yaml
  - id: external-dns
    path: modules/infrastructure/external-dns/module.yaml
