apiVersion: opsd.io/modules/v1alpha1
kind: KubernetesModule

metadata:
  id: external-secrets
  name: External Secrets Operator
  description: Synchronizes external secret backends into Kubernetes Secrets.

spec:
  layer: infrastructure
  source:
    type: helm
    repository: https://charts.external-secrets.io
    chart: external-secrets
    version: 2.12.0
    digest: sha256:4b584136b7311c0af8c8719d377cc5b1a7ef12c2de18f1fdb30614eab75bdeb3
  defaults: defaults.yaml
  schema: schema.yaml
  ownership:
    type: official
    repository: opsd-io/modules-kubernetes
  supported_providers: [digitalocean]
  provider_extensions: {}
  validation:
    mode: strict
